[project]
name = "witnesschain"
description = "Digital notary and witness verification"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.witnesschain]
path = "contracts/witnesschain.clar"

[repl.analysis]
passes = ["check_checker"]
